/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module xor_test (
  input a,
  input b,
  output y
);
  assign y = ((~ a & b) | (a & ~ b));
endmodule
