/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module full_adder (
  input a,
  input b,
  input cin,
  output cout,
  output sum
);
  assign cout = ((cin & a) | (cin & b) | (b & a));
  assign sum = (a ^ b ^ cin);
endmodule
