/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module half_adder (
  input a,
  input b,
  output sum,
  output cry
);
  assign sum = (a ^ b);
  assign cry = (a & b);
endmodule

module incrementer (
  input [3:0] a,
  input inc,
  output cry,
  output [3:0] y
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  assign s0 = a[3];
  assign s3 = a[2];
  assign s6 = a[1];
  assign s9 = a[0];
  half_adder half_adder_i0 (
    .a( s9 ),
    .b( inc ),
    .sum( s10 ),
    .cry( s7 )
  );
  half_adder half_adder_i1 (
    .a( s6 ),
    .b( s7 ),
    .sum( s8 ),
    .cry( s4 )
  );
  half_adder half_adder_i2 (
    .a( s3 ),
    .b( s4 ),
    .sum( s5 ),
    .cry( s1 )
  );
  half_adder half_adder_i3 (
    .a( s0 ),
    .b( s1 ),
    .sum( s2 ),
    .cry( cry )
  );
  assign y[3] = s2;
  assign y[2] = s5;
  assign y[1] = s8;
  assign y[0] = s10;
endmodule

module not_neg (
  input [3:0] a,
  input invert,
  input neg,
  output [3:0] y,
  output cry
);
  wire s0;
  wire [3:0] s1;
  assign s0 = (invert & neg);
  assign s1[3] = (invert ^ a[3]);
  assign s1[2] = (invert ^ a[2]);
  assign s1[1] = (invert ^ a[1]);
  assign s1[0] = (invert ^ a[0]);
  incrementer incrementer_i0 (
    .a( s1 ),
    .inc( s0 ),
    .cry( cry ),
    .y( y )
  );
endmodule

module full_adder (
  input a,
  input b,
  input cin,
  output cout,
  output sum
);
  assign cout = ((cin & a) | (cin & b) | (b & a));
  assign sum = (a ^ b ^ cin);
endmodule

module four_bit_adder (
  input [3:0] a,
  input [3:0] b,
  input cin,
  output [3:0] y,
  output cout,
  output overfl
);
  wire cout_temp;
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  assign s1 = a[3];
  assign s4 = a[2];
  assign s8 = a[1];
  assign s12 = a[0];
  assign s2 = b[3];
  assign s5 = b[2];
  assign s9 = b[1];
  assign s13 = b[0];
  full_adder full_adder_i0 (
    .a( s12 ),
    .b( s13 ),
    .cin( cin ),
    .cout( s10 ),
    .sum( s14 )
  );
  full_adder full_adder_i1 (
    .a( s8 ),
    .b( s9 ),
    .cin( s10 ),
    .cout( s6 ),
    .sum( s11 )
  );
  full_adder full_adder_i2 (
    .a( s4 ),
    .b( s5 ),
    .cin( s6 ),
    .cout( s0 ),
    .sum( s7 )
  );
  full_adder full_adder_i3 (
    .a( s1 ),
    .b( s2 ),
    .cin( s0 ),
    .cout( cout_temp ),
    .sum( s3 )
  );
  assign overfl = (cout_temp ^ s0);
  assign y[3] = s3;
  assign y[2] = s7;
  assign y[1] = s11;
  assign y[0] = s14;
  assign cout = cout_temp;
endmodule

module two_bit_mux (
  input a,
  input b,
  input s,
  output y
);
  assign y = ((a & ~ s) | (b & s));
endmodule

module four_bit_mux (
  input [3:0] a,
  input [3:0] b,
  input sel,
  output [3:0] y
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  assign s0 = a[3];
  assign s3 = a[2];
  assign s6 = a[1];
  assign s9 = a[0];
  assign s1 = b[3];
  assign s4 = b[2];
  assign s7 = b[1];
  assign s10 = b[0];
  two_bit_mux two_bit_mux_i0 (
    .a( s0 ),
    .b( s1 ),
    .s( sel ),
    .y( s2 )
  );
  two_bit_mux two_bit_mux_i1 (
    .a( s3 ),
    .b( s4 ),
    .s( sel ),
    .y( s5 )
  );
  two_bit_mux two_bit_mux_i2 (
    .a( s6 ),
    .b( s7 ),
    .s( sel ),
    .y( s8 )
  );
  two_bit_mux two_bit_mux_i3 (
    .a( s9 ),
    .b( s10 ),
    .s( sel ),
    .y( s11 )
  );
  assign y[3] = s2;
  assign y[2] = s5;
  assign y[1] = s8;
  assign y[0] = s11;
endmodule

module and_add (
  input [3:0] a,
  input [3:0] b,
  input add,
  input cin,
  input pass,
  output [3:0] y,
  output cout,
  output overfl
);
  wire [3:0] s0;
  wire [3:0] s1;
  wire [3:0] s2;
  four_bit_adder four_bit_adder_i0 (
    .a( a ),
    .b( b ),
    .cin( cin ),
    .y( s0 ),
    .cout( cout ),
    .overfl( overfl )
  );
  assign s1[3] = (a[3] & b[3]);
  assign s1[2] = (a[2] & b[2]);
  assign s1[1] = (a[1] & b[1]);
  assign s1[0] = (a[0] & b[0]);
  four_bit_mux four_bit_mux_i1 (
    .a( s1 ),
    .b( s0 ),
    .sel( add ),
    .y( s2 )
  );
  four_bit_mux four_bit_mux_i2 (
    .a( s2 ),
    .b( a ),
    .sel( pass ),
    .y( y )
  );
endmodule

module alu (
  input [3:0] a,
  input invert,
  input [3:0] b,
  input arith,
  input cin,
  input pass,
  output [3:0] y,
  output cout,
  output overfl
);
  wire [3:0] s0;
  not_neg not_neg_i0 (
    .a( a ),
    .invert( invert ),
    .neg( arith ),
    .y( s0 )
  );
  and_add and_add_i1 (
    .a( s0 ),
    .b( b ),
    .add( arith ),
    .cin( cin ),
    .pass( pass ),
    .y( y ),
    .cout( cout ),
    .overfl( overfl )
  );
endmodule
