/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module half_adder (
  input a,
  input b,
  output sum,
  output cry
);
  assign cry = (a & b);
  assign sum = (a ^ b);
endmodule

module incrementer (
  input [3:0] a,
  input inc,
  output [3:0] y,
  output cry
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  assign s0 = a[3];
  assign s3 = a[2];
  assign s6 = a[1];
  assign s9 = a[0];
  half_adder half_adder_i0 (
    .a( s9 ),
    .b( inc ),
    .sum( s10 ),
    .cry( s7 )
  );
  half_adder half_adder_i1 (
    .a( s6 ),
    .b( s7 ),
    .sum( s8 ),
    .cry( s4 )
  );
  half_adder half_adder_i2 (
    .a( s3 ),
    .b( s4 ),
    .sum( s5 ),
    .cry( s1 )
  );
  half_adder half_adder_i3 (
    .a( s0 ),
    .b( s1 ),
    .sum( s2 ),
    .cry( cry )
  );
  assign y[3] = s2;
  assign y[2] = s5;
  assign y[1] = s8;
  assign y[0] = s10;
endmodule

module not_neg (
  input [3:0] a,
  input invert,
  input neg,
  output [3:0] y,
  output cry
);
  wire s0;
  wire [3:0] s1;
  assign s0 = (invert & neg);
  assign s1[3] = (invert ^ a[3]);
  assign s1[2] = (invert ^ a[2]);
  assign s1[1] = (invert ^ a[1]);
  assign s1[0] = (invert ^ a[0]);
  incrementer incrementer_i0 (
    .a( s1 ),
    .inc( s0 ),
    .y( y ),
    .cry( cry )
  );
endmodule

module full_adder (
  input a,
  input b,
  input cin,
  output sum,
  output cout
);
  assign sum = (a ^ b ^ cin);
  assign cout = ((cin & a) | (cin & b) | (a & b));
endmodule

module four_bit_adder (
  input [3:0] a,
  input [3:0] b,
  input cin,
  output [3:0] y,
  output cout,
  output overfl
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire cout_temp;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  assign s0 = a[3];
  assign s4 = a[2];
  assign s8 = a[1];
  assign s12 = a[0];
  assign s1 = b[3];
  assign s5 = b[2];
  assign s9 = b[1];
  assign s13 = b[0];
  full_adder full_adder_i0 (
    .a( s12 ),
    .b( s13 ),
    .cin( cin ),
    .sum( s14 ),
    .cout( s10 )
  );
  full_adder full_adder_i1 (
    .a( s8 ),
    .b( s9 ),
    .cin( s10 ),
    .sum( s11 ),
    .cout( s6 )
  );
  full_adder full_adder_i2 (
    .a( s4 ),
    .b( s5 ),
    .cin( s6 ),
    .sum( s7 ),
    .cout( s2 )
  );
  full_adder full_adder_i3 (
    .a( s0 ),
    .b( s1 ),
    .cin( s2 ),
    .sum( s3 ),
    .cout( cout_temp )
  );
  assign y[3] = s3;
  assign y[2] = s7;
  assign y[1] = s11;
  assign y[0] = s14;
  assign overfl = (cout_temp ^ s2);
  assign cout = cout_temp;
endmodule

module two_bit_mux (
  input b,
  input s,
  input a,
  output y
);
  assign y = ((a & ~ s) | (b & s));
endmodule

module four_bit_mux (
  input [3:0] a,
  input [3:0] b,
  input sel,
  output [3:0] y
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  assign s1 = a[3];
  assign s4 = a[2];
  assign s7 = a[1];
  assign s10 = a[0];
  assign s0 = b[3];
  assign s3 = b[2];
  assign s6 = b[1];
  assign s9 = b[0];
  two_bit_mux two_bit_mux_i0 (
    .b( s0 ),
    .s( sel ),
    .a( s1 ),
    .y( s2 )
  );
  two_bit_mux two_bit_mux_i1 (
    .b( s3 ),
    .s( sel ),
    .a( s4 ),
    .y( s5 )
  );
  two_bit_mux two_bit_mux_i2 (
    .b( s6 ),
    .s( sel ),
    .a( s7 ),
    .y( s8 )
  );
  two_bit_mux two_bit_mux_i3 (
    .b( s9 ),
    .s( sel ),
    .a( s10 ),
    .y( s11 )
  );
  assign y[3] = s2;
  assign y[2] = s5;
  assign y[1] = s8;
  assign y[0] = s11;
endmodule

module and_add (
  input [3:0] a,
  input [3:0] b,
  input add,
  input cin,
  input pass,
  output [3:0] y,
  output cout,
  output overfl
);
  wire [3:0] s0;
  wire [3:0] s1;
  wire [3:0] s2;
  four_bit_adder four_bit_adder_i0 (
    .a( a ),
    .b( b ),
    .cin( cin ),
    .y( s0 ),
    .cout( cout ),
    .overfl( overfl )
  );
  assign s1[3] = (a[3] & b[3]);
  assign s1[2] = (a[2] & b[2]);
  assign s1[1] = (a[1] & b[1]);
  assign s1[0] = (a[0] & b[0]);
  four_bit_mux four_bit_mux_i1 (
    .a( s1 ),
    .b( s0 ),
    .sel( add ),
    .y( s2 )
  );
  four_bit_mux four_bit_mux_i2 (
    .a( s2 ),
    .b( a ),
    .sel( pass ),
    .y( y )
  );
endmodule

module alu (
  input [3:0] a,
  input [3:0] b,
  input invert,
  input arith,
  input pass,
  input cin,
  output [3:0] y,
  output cout,
  output overfl
);
  wire [3:0] s0;
  not_neg not_neg_i0 (
    .a( a ),
    .invert( invert ),
    .neg( arith ),
    .y( s0 )
  );
  and_add and_add_i1 (
    .a( s0 ),
    .b( b ),
    .add( arith ),
    .cin( cin ),
    .pass( pass ),
    .y( y ),
    .cout( cout ),
    .overfl( overfl )
  );
endmodule

module DIG_D_FF_AS_1bit
#(
    parameter Default = 0
)
(
   input Set,
   input D,
   input C,
   input Clr,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q  = ~state;

    always @ (posedge C or posedge Clr or posedge Set)
    begin
        if (Set)
            state <= 1'b1;
        else if (Clr)
            state <= 'h0;
        else
            state <= D;
    end

    initial begin
        state = Default;
    end
endmodule

module four_bit_reg (
  input [3:0] d,
  input enable,
  input reset,
  input clk,
  output [3:0] q
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire [3:0] q_temp;
  wire [3:0] s8;
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i0 (
    .Set( 1'b0 ),
    .D( s0 ),
    .C( clk ),
    .Clr( reset ),
    .Q( s1 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i1 (
    .Set( 1'b0 ),
    .D( s2 ),
    .C( clk ),
    .Clr( reset ),
    .Q( s3 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i2 (
    .Set( 1'b0 ),
    .D( s4 ),
    .C( clk ),
    .Clr( reset ),
    .Q( s5 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i3 (
    .Set( 1'b0 ),
    .D( s6 ),
    .C( clk ),
    .Clr( reset ),
    .Q( s7 )
  );
  four_bit_mux four_bit_mux_i4 (
    .a( q_temp ),
    .b( d ),
    .sel( enable ),
    .y( s8 )
  );
  assign q_temp[3] = s5;
  assign q_temp[2] = s7;
  assign q_temp[1] = s3;
  assign q_temp[0] = s1;
  assign s4 = s8[3];
  assign s6 = s8[2];
  assign s2 = s8[1];
  assign s0 = s8[0];
  assign q = q_temp;
endmodule
module DIG_RAMDualPort
#(
    parameter Bits = 8,
    parameter AddrBits = 4
)
(
  input [(AddrBits-1):0] A,
  input [(Bits-1):0] Din,
  input str,
  input C,
  input ld,
  output [(Bits-1):0] D
);
  reg [(Bits-1):0] memory[0:((1 << AddrBits) - 1)];

  assign D = ld? memory[A] : 'hz;

  always @ (posedge C) begin
    if (str)
      memory[A] <= Din;
  end
initial
begin
	$readmemh("ram_vals.txt",memory);
end
endmodule


module program_ram  (
  input [3:0] addr,
  input [3:0] data_in,
  input clk,
  input write,
  output [3:0] data_out
);
  // program\_ram
  DIG_RAMDualPort #(
    .Bits(4),
    .AddrBits(4)
  )
  DIG_RAMDualPort_i0 (
    .A( addr ),
    .Din( data_in ),
    .str( write ),
    .C( clk ),
    .ld( 1'b1 ),
    .D( data_out )
  );
endmodule

module brainless (
  input [3:0] data_in,
  input [3:0] addr_bus,
  input load_acc,
  input read,
  input acc_to_db,
  input pass,
  input arith,
  input invert,
  input reset,
  input write,
  input clk,
  output [3:0] data_bus,
  output [3:0] alu_out,
  output [3:0] accum
);
  wire [3:0] data_bus_temp;
  wire [3:0] accum_temp;
  wire [3:0] alu_out_temp;
  wire [3:0] s0;
  wire [3:0] s1;
  alu alu_i0 (
    .a( data_bus_temp ),
    .b( accum_temp ),
    .invert( invert ),
    .arith( arith ),
    .pass( pass ),
    .cin( 1'b0 ),
    .y( alu_out_temp )
  );
  four_bit_reg four_bit_reg_i1 (
    .d( alu_out_temp ),
    .enable( load_acc ),
    .reset( reset ),
    .clk( clk ),
    .q( accum_temp )
  );
  four_bit_mux four_bit_mux_i2 (
    .a( data_in ),
    .b( s0 ),
    .sel( read ),
    .y( s1 )
  );
  four_bit_mux four_bit_mux_i3 (
    .a( s1 ),
    .b( accum_temp ),
    .sel( acc_to_db ),
    .y( data_bus_temp )
  );
  program_ram program_ram_i4 (
    .addr( addr_bus ),
    .data_in( data_bus_temp ),
    .clk( clk ),
    .write( write ),
    .data_out( s0 )
  );
  assign data_bus = data_bus_temp;
  assign alu_out = alu_out_temp;
  assign accum = accum_temp;
endmodule